# Generated by Django 4.0.4 on 2022-05-07 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='notification_preference',
            field=models.CharField(choices=[('None', 'None'), ('Email', 'EMail')], default='None', help_text='If you would like to receive notifications from us please select your preference.', max_length=10),
        ),
    ]
