# Generated by Django 4.0.4 on 2022-05-06 00:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_group', models.CharField(blank=True, default='', max_length=150, null=True)),
                ('purpose', models.TextField(blank=True, default='', null=True)),
                ('qualified_intentions', models.TextField(blank=True, default='', null=True)),
                ('service_group_type', models.CharField(choices=[('---', '---'), ('1) Esoteric', '1) Esoteric'), ('2) Exoteric', '2) Exoteric')], default='---', max_length=20)),
                ('service_group_status', models.CharField(choices=[('1) Active', '1) Active'), ('2) Inactive', '2) Inactive')], default='1) Active', max_length=20)),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('members', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('service_group_creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='service_group_creator', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Service Group',
                'verbose_name_plural': 'Service Groups',
            },
        ),
    ]
