# Generated by Django 4.0.4 on 2022-05-08 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0005_alter_objective_options_objective_date_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicegroup',
            name='service_group',
            field=models.CharField(blank=True, default='', max_length=150, null=True, unique=True),
        ),
    ]
