# Generated by Django 4.0.4 on 2022-05-08 22:04

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0006_alter_servicegroup_service_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objective',
            name='objective_statement',
            field=tinymce.models.HTMLField(blank=True, default='SMART (Specific, Measurable, Achievable, Relevant, Timely) Objective...', help_text='An objective statement empowers a Group throughout the service activity. An essential question for \n        any group is to ask, Why is the accomplishment of this objective important to the EGA Divine Plan?\n\n        Elements of an Objective Statement that will make it stronger are SMART: Specific (state what the Group will do)\n        ; Measurable (provide a way to evaluate through metrics or data); Achievable (possible to accomplish, \n        attainable); Relevant (makes sense in the context of the EGA Divine Plan); Time-bound (states when the objective \n         will be accomplished).', null=True),
        ),
    ]
