# Generated by Django 4.0.4 on 2022-05-08 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0007_alter_objective_objective_statement'),
    ]

    operations = [
        migrations.AddField(
            model_name='objective',
            name='objective_status',
            field=models.CharField(choices=[('1) Not started', '1) Not started'), ('2) In progress', '2) In progress'), ('3) Deferred', '3) Deferred'), ('3) Complete', '3) Complete'), ('Cancelled', 'Cancelled')], default='1) Not started', max_length=20),
        ),
    ]
