# Generated by Django 4.0.4 on 2022-05-09 00:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0009_peep_lee'),
    ]

    operations = [
        migrations.AddField(
            model_name='peep',
            name='service_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='PEeP_service_group', to='ops.servicegroup'),
        ),
        migrations.AlterField(
            model_name='lee',
            name='whurthy_application',
            field=models.CharField(choices=[('CCL', 'CCL'), ('Events', 'Events'), ('Ops', 'Ops'), ('Users', 'Users'), ('CCL', 'CCL'), ('Other', 'Other')], default='PIPS', help_text='Please select the application that this entry applies to.', max_length=100),
        ),
    ]
