# Generated by Django 4.0.4 on 2022-05-09 02:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0012_alter_lee_whurthy_application_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='objective',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ops.objective'),
        ),
    ]
