# Generated by Django 4.0.4 on 2022-05-09 02:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0013_task_objective'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='service_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='task_service_group', to='ops.servicegroup'),
        ),
    ]
